### ISSUE TITLE
Issues running

### ISSUE THREAD

**Issue by binnnnnny** [zideliu/StyleDrop-PyTorch#26]
Hi, Thank you for your great work.

When I try to run training code
```python
!accelerate launch --mixed_precision fp16 train_t2i_custom_v2.py --config=configs/custom.py\
```

I receive the following error:
```
TypeError: __init__() got an unexpected keyword argument 'debug'
```

Thanks in advance :)

**Comment by zideliu** [comment]
Can you provide more detailed error information? For example, which file reported an error?

**Comment by isabellapu** [comment]
I get the same problem:

/usr/lib/python3/dist-packages/requests/__init__.py:87: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/u/ipu/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/u/ipu/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/u/ipu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/u/ipu/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/u/ipu/.local/lib/python3.10/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug'

**Comment by zideliu** [comment]
I think this is probably a problem with the running environment? You can see the link below to install
[Dependencies](https://github.com/zideliu/StyleDrop-PyTorch#dependencies) here
